### ISSUE TITLE
Create a Use-case diagram

### ISSUE THREAD

**Issue by antoniofmoraes** [antoniofmoraes/financial-management-app#3]

**Comment by antoniofmoraes** [comment]
https://www.figma.com/file/L1KElLgv7SgSy2K8YT8z1R/Untitled?node-id=3%3A89

**Comment by FelipeIvanaga** [comment]
![image](https://user-images.githubusercontent.com/30486121/149826587-d9c2ac07-863d-46e3-93a3-9f8f8f22f519.png)

https://www.figma.com/file/L1KElLgv7SgSy2K8YT8z1R/Financial-APP?node-id=0%3A1
